version: '3'

services:
        api:
                build: .
                env_file: .env
                environment:
                        MONGODB_URI: mongodb://mongo:27017/haylun
                depends_on:
                        - mongo
                ports:
                        - "8080:8080"
        mongo:
                image: mongo
                ports:
                        - "27017:27017"
